# Generated by Django 4.0.5 on 2022-06-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='https://image-bucket6755.s3.amazonaws.com/media/'),
        ),
    ]
