services:
  web:
    container_name: image-uploader
    image: public.ecr.aws/d6w2o4u5/image-uploader
    command: gunicorn -b 0.0.0.0:8000 --timeout 300 --workers 4 image_uploader.wsgi:application
    ports:
      - 8001:8000
    env_file:
      - ./.env.prod
    volumes:
      - ./:/usr/src/app
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

version: '3.2'
